### ISSUE TITLE
cp: can't stat 'remotecontrol': No such file or directory

### ISSUE THREAD

**Issue by Rashadse** [dit168-group7/Group-7---DIT168#15]
https://github.com/dit168-group7/Group-7---DIT168/blob/4e5cc46f4b70ad5e2b93c2cc3f5870ec3108dfa3/remotecontrol/Dockerfile#L17

**Comment by Rashadse** [comment]
can't figure out why this won't work

**Comment by maansthoernvik** [comment]
I think that's not the name of your executable

**Comment by Rashadse** [comment]
solved
